### ISSUE TITLE
UI design changes - Part 1

### ISSUE THREAD

**Issue by mpivchev** [nextcloud/ios#2744]
### General points to be taken into account when working on these:

- Check how it looks compared to other contemporary iOS apps (Dropbox, Google Drive, Onedrive etc.)
- Consider iOS UI guidelines
- Check light/dark mode consistency
- Check phone/tablet variants

### Part 1 are changes that are prioritized:

- [x] **Tab bars and navigation bars should be translucent** -> https://github.com/nextcloud/ios/pull/2757
- [x] **Add a 3 dot menu on the top right, add many actions there (see Apple iOS Files app for example)** -> https://github.com/nextcloud/ios/pull/2761
- "Select" can be moved there
- @marinofaggiana mentioned already working on something similar. Contact him for details.
  - [x] Following previous point, Grid/list switcher icon and sort button take up a lot of vertical space -> also move both sort and view switcher into 3 dot menu in top right:
        
     ![image](https://github.com/nextcloud/ios/assets/6960329/b2bf6387-c0b8-4030-905a-efb2dcd18c7e)

- [x] **Remove full name from top left corner, only keep avatar** -> https://github.com/nextcloud/ios/pull/2743

    ![image](https://github.com/nextcloud/ios/assets/6960329/962a3861-b8ea-4d3a-ba9a-030ba9e39dff)

- [x] **Clean up file actions in general to reduce length of menu:** -> https://github.com/nextcloud/ios/pull/2766

   <img width="259" alt="image" src="https://github.com/nextcloud/ios/assets/6960329/7cf3c114-bffc-4ec9-b79d-c5f8793aec1a">

 - Some actions don't need to be shown, some must be renamed 
  - Maybe there could be collapsible action menu items, some actions are grouped in a collapsible menu (like new media view)
  - We use custom action views for a lot of screens, ideally we should use only native iOS context menus
  - Copy, Move, Copy or move in files, Save locally etc. can be moved to their own Share sheet (see Instagram)
      - [x] As mentioned above, we have a "Copy" option and a "Copy or move in app" option, very confusing.  Must be fixed.
           -  "Copy to clipboard" is already available in the share sheet which can be opened via "Open with …" so the "Copy" action can be removed, and "Copy or move in app" should be renamed to "Move or copy" to be the same as in the web interface.

- [x] **Creating a new item** - https://github.com/nextcloud/ios/pull/2783

   <img width="259" alt="image" src="https://github.com/nextcloud/ios/assets/6960329/9fe4c087-d38c-43b7-9411-bbb744189ba7">

- The entire intermediate step can be skipped, file should be called "New text document" by default
   - Besides, the screen for this looks old and non iOS-like
- After the file is created there should be some sort of loading feedback. Currently the view is just white for a while until the skeleton screen of text shows up

--------------------------------
**Not planned**:
- **+ button has non standard position and style**

![SCR-20240117-lxt](https://github.com/nextcloud/ios/assets/6960329/d93e383d-29dc-4e1f-b1eb-5d957e8cf424)

**Comment by tobiasKaminsky** [comment]
> > The Sharing screen is really complicated, so apart from simple changes the rest is almost impossible to touch without revolutionising the code, it would lend itself very well to a design in SwiftUI but would require quite a bit of time
> 
> In that case I can make a point that the redesign should be simple and only improving upon the current implementation, not something super complex. What do you think?
> 
> cc [@jancborchardt](https://github.com/jancborchardt) [@tobiasKaminsky](https://github.com/tobiasKaminsky)

Then please put Sharing as part3 in a new issue.
